<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net10.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable></PropertyGroup><ItemGroup><FrameworkReference Include="Microsoft.AspNetCore.App"/><Reference Include="EmailValidation.Domain"><HintPath>../../../../src/EmailValidation.Domain/bin/Debug/net10.0/EmailValidation.Domain.dll</HintPath></Reference><Reference Include="EmailValidation.Core"><HintPath>../../../../src/EmailValidation.Core/bin/Debug/net10.0/EmailValidation.Core.dll</HintPath></Reference><Reference Include="EmailValidation.Application"><HintPath>../../../../src/EmailValidation.Application/bin/Debug/net10.0/EmailValidation.Application.dll</HintPath></Reference><Reference Include="EmailValidation.Infrastructure"><HintPath>../../../../src/EmailValidation.Infrastructure/bin/Debug/net10.0/EmailValidation.Infrastructure.dll</HintPath></Reference></ItemGroup></Project>
