domains = { "validation.email.digitalwarehouse.io", "srs.validation.email.digitalwarehouse.io" }
srs-domain = "srs.validation.email.digitalwarehouse.io"
socketmap = inet:127.0.0.1:10003
keep-alive = 30
original-envelope = embedded
secrets-file = "/var/lib/postsrsd/postsrsd.secret"
separator = "="
hash-length = 4
hash-minimum = 4
always-rewrite = off
unprivileged-user = "postsrsd"
chroot-dir = "/var/lib/postsrsd"
syslog = off
debug = off
